let myDate =new Date()
// console.log(myDate.toString())
// console.log(myDate.toDateString())
// console.log(myDate.toISOString())
// console.log(myDate.toJSON())
// console.log(myDate.toLocaleDateString())
// console.log(myDate.toTimeString())
// console.log(typeof myDate)

let myNew = new Date(2002, 7, 10)
console.log(myNew.toDateString())
let myNew1 = new Date() 
console.log(myNew1)